<?php
defined('BASEPATH') OR exit('No direct script access allowed');

/**
 * Created by PhpStorm.
 * User: pijush
 * Date: 2/11/16
 * Time: 6:33 PM
 */
class Sign_up extends MY_Controller
{
    public function __construct()
    {
        parent::__construct();
    }


    /*---------------------------------------------------------------------------------------------------------------
     *|This controller is responsible for loading the SignUp form(view) in the "view/public/body.php"($form==signup)|
     *---------------------------------------------------------------------------------------------------------------
     */
    function index()
    {
        if ($this->input->post()) {
            $re_post = $this->input->post(NULL,TRUE); // Reciving post array after xss filtering for futher security check 
            $this->load->library('my_security');
            if ($this->form_validation->run('user_signup') == TRUE && $this->my_security->is_this_empty($re_post)!=TRUE) {

                $this->load->model('Authors');

                if ($this->Authors->is_author('email',$re_post['useremail']) != TRUE) {

                    if ($this->Authors->create_author($re_post['username'], $re_post['useremail'], $re_post['timezone'], $re_post['userpassword_one']) == TRUE) {

                        $this->load->library('my_mail');

                        if ($this->my_mail->send_activation_email(trim($re_post['useremail']), $this->Authors->is_author('email', trim($re_post['useremail']), 'author_id'), site_url('Sign_up/activate_author_account')) == TRUE) {

                            $this->session->set_flashdata('error', 'An Email has been sent to your email id to activate your account!');

                            redirect('Sign_up');
                        }
                    } else {
                        $this->session->set_flashdata('error', 'Database Error, please contact the admin.');
                    }
                } else {
                    $this->session->set_flashdata('error', 'Try again, using different email id.');
                }
            } else {
                $this->session->set_flashdata('error', 'Error(s) in form.');
            }
        }
        $this->load->model('Time');
        $timezone_object = $this->Time->provide_timezone_list();
        $head = (array('sign' => 'signin', 'form' => 'signup', 'time_zones' => $timezone_object));
        $this->public_view($head, '', '', '');
    }


    /*--------------------------------------------------------------------------------------------------------------------
     *|This controller is responsible for the post-action on activation email generated by "controller/Sign_up.php/index"|
     *--------------------------------------------------------------------------------------------------------------------
     */
    public function activate_author_account($link = null)
    {
        if ($link != null) {
            $link = $this->security->xss_clean($link);
            $this->load->library('my_mail');
            $link = explode('/',$this->my_mail->decode_email_activation_link(trim($link)));
            $link = $this->security->xss_clean($link);



            if ($this->form_validation->valid_email($link[0])) {
                $this->load->Model('Authors');
                if ($link[1] == $this->Authors->is_author('email', $link[0], 'author_id') && $this->Authors->is_author('email', $email, 'author_verified') == 0) {
                    if ($this->Authors->verify_author($email) == TRUE) {
                        $this->session->set_flashdata('error0', 'Account has been activated, Please login!');
                        redirect('Public_login');
                    }
                } elseif ($this->Authors->is_author('email', $email) == TRUE && $this->Authors->is_author('email', $email, 'author_verified') == 1) {
                    $this->session->set_flashdata('error0', 'Account already active, Please login!');
                    redirect('Public_login');
                } elseif ($this->Authors->is_author('email', $email) == FALSE) {
                    redirect('Sign_up');
                }
            }

        } else {

            redirect('Sign_up');
        }
    }
}